services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    networks:
      - app-network

networks:
  app-network:
    external: true
    name: app-network