services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: on-failure
    profiles: [redis, all]
    networks:
      - app-network
    mem_limit: 128m
    mem_reservation: 64m

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    ports:
      - "${ZOOKEEPER_PORT:-2181}:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      KAFKA_HEAP_OPTS: "-Xms128m -Xmx256m"
    profiles: [zookeeper, all]
    networks:
      - app-network
    mem_limit: 384m
    mem_reservation: 256m
  
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    ports:
      - "${KAFKA_PORT:-9092}:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xms256m -Xmx512m"
      KAFKA_JVM_PERFORMANCE_OPTS: "-XX:MetaspaceSize=96m -XX:+UseG1GC -XX:MaxGCPauseMillis=20 -XX:InitiatingHeapOccupancyPercent=35"
    profiles: [kafka, all]
    networks:
      - app-network
    mem_limit: 768m
    mem_reservation: 512m

  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.1
    depends_on: [kafka]
    ports: 
      - "${CONFLUENT_PORT:-8081}:8081"
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:9092
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_HEAP_OPTS: "-Xms128m -Xmx256m"
    profiles: [schema-registry, all]
    networks:
      - app-network

  akhq:
      image: tchiotludo/akhq:latest
      ports:
        - "8080:8080"
      environment:
        AKHQ_CONFIGURATION: |
          akhq:
            connections:
              docker-kafka:
                properties:
                  bootstrap.servers: "kafka:9092"
                schema-registry:
                  url: "http://schema-registry:8081"
      profiles: [akhq, all]
      depends_on: [kafka, schema-registry]
      networks:
        - app-network

  integration_service:
    build:
      context: .
      dockerfile: microservices/integration_service/Dockerfile
      args:
        NEXTPLORE_SDK: libs/.wheelhouse/nextplore_sdk-0.1.0-py3-none-any.whl
        KAFKA_MESSAGING: libs/.wheelhouse/kafka_messaging-0.1.0-py3-none-any.whl
        SVC_INTEGRATION_CONTRACTS: libs/.wheelhouse/svc_integration_contracts-0.1.0-py3-none-any.whl
    container_name: integration_service
    ports:
      - "${INTEGRATION_PORT:-8001}:8001"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - PYTHONUNBUFFERED=1
      - REDIS_URL=${REDIS_URL}
      - FERNET_KEY=${FERNET_KEY}
      - KAFKA_GROUP_PREFIX=${KAFKA_GROUP_PREFIX}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USR_INTEGRATION_SERVICE=${DB_USR_INTEGRATION_SERVICE}
      - DB_PWD_INTEGRATION_SERVICE=${DB_PWD_INTEGRATION_SERVICE}
      - AWS_ROLE_ARN=${AWS_ROLE_ARN}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_REGION=${AWS_REGION}
      - GCP_ACCESS_KEY=${GCP_ACCESS_KEY}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID_CRYPTO}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID_CRYPTO}
      - AZURE_CLIENT_SECRET=${AZURE_CLIENT_SECRET}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - AKV_URL=${AKV_URL}
    profiles: [integration_service, all]
    volumes:
      - ~/.gcp-keys/gcp-access-key.json:/app/gcp-access-key.json:ro
    depends_on:
      - kafka
      - redis
    restart: on-failure
    networks:
      - app-network
    mem_limit: 384m
    mem_reservation: 256m

  embedding_service:
    build:
      context: .
      dockerfile: microservices/embedding_service/Dockerfile
      args:
        NEXTPLORE_SDK: libs/.wheelhouse/nextplore_sdk-0.1.0-py3-none-any.whl
        KAFKA_MESSAGING: libs/.wheelhouse/kafka_messaging-0.1.0-py3-none-any.whl
        SVC_EMBEDDING_CONTRACTS: libs/.wheelhouse/svc_embedding_contracts-0.1.0-py3-none-any.whl
    container_name: embedding_service
    ports:
      - "${EMBEDDING_PORT:-8002}:8001"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - PYTHONUNBUFFERED=1
      - REDIS_URL=${REDIS_URL}
      - KAFKA_GROUP_PREFIX=${KAFKA_GROUP_PREFIX}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    profiles: [embedding_service, all]
    depends_on:
      - kafka
      - redis
    restart: on-failure
    networks:
      - app-network
    mem_limit: 384m
    mem_reservation: 256m

  vector_service:
    build:
      context: .
      dockerfile: microservices/vector_service/Dockerfile
      args:
        NEXTPLORE_SDK: libs/.wheelhouse/nextplore_sdk-0.1.0-py3-none-any.whl
        KAFKA_MESSAGING: libs/.wheelhouse/kafka_messaging-0.1.0-py3-none-any.whl
        SVC_VECTOR_CONTRACTS: libs/.wheelhouse/svc_vector_contracts-0.1.0-py3-none-any.whl
    container_name: vector_service
    ports:
      - "${VECTOR_PORT:-8003}:8001"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - PYTHONUNBUFFERED=1
      - REDIS_URL=${REDIS_URL}
      - KAFKA_GROUP_PREFIX=${KAFKA_GROUP_PREFIX}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USR_VECTOR_SERVICE=${DB_USR_VECTOR_SERVICE}
      - DB_PWD_VECTOR_SERVICE=${DB_PWD_VECTOR_SERVICE}
      - DB_NAME=${DB_NAME}
      - QDRANT_CLUSTER_HOST=${QDRANT_CLUSTER_HOST}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    profiles: [vector_service, all]
    depends_on:
      - kafka
      - redis
    restart: on-failure
    networks:
      - app-network
    mem_limit: 384m
    mem_reservation: 256m

  ai_orm_context_service:
    build:
      context: .
      dockerfile: microservices/ai_orm_context_service/Dockerfile
      args:
        NEXTPLORE_SDK: libs/.wheelhouse/nextplore_sdk-0.1.0-py3-none-any.whl
        SVC_AI_ORM_CONTEXT_CONTRACTS: libs/.wheelhouse/svc_ai_orm_context_contracts-0.1.0-py3-none-any.whl
    container_name: ai_orm_context_service
    depends_on:
      - redis
    ports:
      - "${AI_ORM_CONTEXT_PORT:-8004}:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_URL=${REDIS_URL}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
    profiles: [ai_orm_context_service, all]
    restart: on-failure
    networks:
      - app-network
    mem_limit: 384m
    mem_reservation: 256m

  orchestration_service:
    build:
      context: .
      dockerfile: nextplore_orchestrator/Dockerfile
      args:
        NEXTPLORE_SDK: libs/.wheelhouse/nextplore_sdk-0.1.0-py3-none-any.whl
        KAFKA_MESSAGING: libs/.wheelhouse/kafka_messaging-0.1.0-py3-none-any.whl
        SVC_AI_ORM_CONTEXT_CONTRACTS: libs/.wheelhouse/svc_ai_orm_context_contracts-0.1.0-py3-none-any.whl
        SVC_EMBEDDING_CONTRACTS: libs/.wheelhouse/svc_embedding_contracts-0.1.0-py3-none-any.whl
        SVC_INTEGRATION_CONTRACTS: libs/.wheelhouse/svc_integration_contracts-0.1.0-py3-none-any.whl
        SVC_NEXTPLORE_ORCHESTRATOR_CONTRACTS: libs/.wheelhouse/svc_nextplore_orchestrator_contracts-0.1.0-py3-none-any.whl
        SVC_VECTOR_CONTRACTS: libs/.wheelhouse/svc_vector_contracts-0.1.0-py3-none-any.whl
    container_name: orchestration_service
    depends_on:
      - kafka
      - redis
    ports:
      - "${ORCHESTRATION_PORT:-8005}:8001"
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS}
      - PYTHONUNBUFFERED=1
      - KAFKA_GROUP_PREFIX=${KAFKA_GROUP_PREFIX}
      - FERNET_KEY=${FERNET_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - AZURE_CLIENT_ID=${AZURE_CLIENT_ID}
      - AZURE_TENANT_ID=${AZURE_TENANT_ID}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - AZURE_AUTHORITY=${AZURE_AUTHORITY}
      - ISSUER=${ISSUER}
      - JWKS_URL=${JWKS_URL}
      - JWT_ALGORITHMS=${JWT_ALGORITHMS}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    profiles: [orchestration_service, all]
    restart: on-failure
    networks:
      - app-network
    mem_limit: 384m
    mem_reservation: 256m

networks:
  app-network:
    name: app-network
