sonar.organization=unsigned-long-int
sonar.projectKey=nextplore

sonar.projectName=Nextplore
sonar.projectVersion=1.0

sonar.sources=.
sonar.tests=\
  libs/*/tests,\
  microservices/*/tests

sonar.language=py
sonar.python.version=3.13

sonar.python.coverage.reportPaths=coverage.xml

sonar.exclusions=\
  **/tests/**,\
  **/test_*.py,\
  **/*_test.py,\
  **/migrations/**,\
  **/__pycache__/**,\
  **/venv/**,\
  **/.venv/**,\
  **/.pytest_cache/**,\
  **/htmlcov/**,\
  **/*.pyc,\
  **/dist/**,\
  **/build/**,\
  **/.coverage,\
  **/coverage.xml,\
  **/node_modules/**,\
  **/.eggs/**,\
  **/*.egg-info/**

sonar.test.inclusions=\
  **/tests/**,\
  **/test_*.py,\
  **/*_test.py

sonar.sourceEncoding=UTF-8

sonar.cpd.exclusions=\
  **/tests/**,\
  **/migrations/**
