{
    "type": "record",
    "namespace": "com.nextplore.embedding",
    "name": "CrawlMetaEmbedded",
    "fields": [
        {"name": "event_name", "type": "string"},
        {"name": "version", "type": "string"},
        {"name": "event_id", "type": {"type": "string", "logicalType": "uuid"}},
        {"name": "timestamp", "type": {"type": "long", "logicalType": "timestamp-micros"}},
        {"name": "user_id", "type": {"type": "string", "logicalType": "uuid"}},
        {"name": "organization_id", "type": {"type": "string", "logicalType": "uuid"}},
        {
            "name": "orm_embedding", 
            "type": {
                "type": "array", 
                "items": {
                    "type": "record",
                    "name": "ORMEmbedding",
                    "namespace": "com.nextplore.embedding",
                    "fields": [
                        {"name": "integration_id", "type": {"type":"string","logicalType":"uuid"}},
                        {"name": "schema_name", "type": "string"},
                        {"name": "table_name", "type": "string"},
                        {
                            "name": "table_meta",
                            "type": {
                                "type": "record",
                                "name": "TableMeta",
                                "namespace": "com.nextplore.embedding",
                                "fields": [
                                    {"name": "integration_id", "type": {"type":"string","logicalType":"uuid"}},
                                    {"name": "integration_name", "type": "string"},
                                    {"name": "integration_descr", "type": "string"},
                                    {"name": "schema_name", "type": "string"},
                                    {"name": "table_name", "type": "string"},
                                    {"name": "column_names", "type": {"type":"array","items":"string"}}
                                ]
                            }
                        },
                        {"name": "embedding", "type": {"type":"array","items":"double"}}
                    ]
                }
            }
        }
    ]
}
