# generated by datamodel-codegen:
#   filename:  openapi.patched.json
#   timestamp: 2026-03-08T17:50:55+00:00

from pydantic import UUID4, BaseModel, Field, RootModel


class ModelInfo(BaseModel):
    provider: str = Field(..., title="Provider")
    model_id: str = Field(..., title="Model Id")
    label: str = Field(..., title="Label")
    tags: list[str] = Field(..., title="Tags")


class ORMContextResponse(BaseModel):
    integration: UUID4 = Field(..., title="Integration")
    schema_name: str = Field(..., title="Schema Name")
    class_name: str = Field(..., title="Class Name")
    table_name: str = Field(..., title="Table Name")
    column_names: list[str] = Field(..., title="Column Names")
    column_aggregates: list[dict[str, str]] = Field(..., title="Column Aggregates")
    column_filters: list[dict[str, str | int]] = Field(..., title="Column Filters")


class Context(BaseModel):
    integration_registry_repr: str = Field(..., title="Integration Registry Repr")
    integrations_enum: list[str] = Field(..., title="Integrations Enum")
    schemas_enum: list[str] = Field(..., title="Schemas Enum")
    tables_enum: list[str] = Field(..., title="Tables Enum")
    columns_enum: list[str] = Field(..., title="Columns Enum")
    filter_op_enum: list[str] = Field(..., title="Filter Op Enum")
    agg_funcs_enum: list[str] = Field(..., title="Agg Funcs Enum")


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")


class ResponseGetModelsV1AiOrmModelsGet(RootModel[list[ModelInfo]]):
    root: list[ModelInfo] = Field(..., title="Response Get Models V1 Ai Orm Models Get")


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(default=None, title="Detail")


class ORMContextRequest(BaseModel):
    provider: str = Field(..., title="Provider")
    model_id: str = Field(..., title="Model Id")
    query: str = Field(..., title="Query")
    context: Context
