# generated by datamodel-codegen:
#   filename:  openapi.patched.json
#   timestamp: 2026-03-08T17:50:55+00:00

from pydantic import UUID4, BaseModel, Field, RootModel
from typing import List, Dict, Any, Optional


class ModelInfo(BaseModel):
    provider: str = Field(..., title="Provider")
    model_id: str = Field(..., title="Model Id")
    label: str = Field(..., title="Label")
    tags: list[str] = Field(..., title="Tags")


class ORMContextResponse(BaseModel):
    datastore: UUID4 = Field(..., title="Data Store")
    schema_name: str = Field(..., title="Schema Name")
    class_name: str = Field(..., title="Class Name")
    table_name: str = Field(..., title="Table Name")
    column_names: list[str] = Field(..., title="Column Names")
    column_aggregates: list[dict[str, str]] = Field(..., title="Column Aggregates")
    column_filters: list[dict[str, str | int]] = Field(..., title="Column Filters")

class SchemaEntry(BaseModel):
    tables: Dict[str, List[str]]

class DataStoreEntry(BaseModel):
    schemas: Dict[str, SchemaEntry]

class LlmOutputSpecs(BaseModel):
    datastore_registry_repr: str = Field(..., title="Data Store Registry Repr")
    datastores_enum: list[str] = Field(..., title="Data Stores Enum")
    schemas_enum: list[str] = Field(..., title="Schemas Enum")
    tables_enum: list[str] = Field(..., title="Tables Enum")
    columns_enum: list[str] = Field(..., title="Columns Enum")
    filter_op_enum: list[str] = Field(..., title="Filter Op Enum")
    agg_funcs_enum: list[str] = Field(..., title="Agg Funcs Enum")
    table_columns_registry: Dict[str, DataStoreEntry] = Field(..., title="Table Columns Registry")


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")


class ResponseGetModelsV1AiOrmModelsGet(RootModel[list[ModelInfo]]):
    root: list[ModelInfo] = Field(..., title="Response Get Models V1 Ai Orm Models Get")


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(default=None, title="Detail")


class UserLlmConfig(BaseModel):
    api_base: str = Field(..., title="API Base URL")
    connection_params: Dict[str, Any] = Field(..., title="Connection Params")
    max_tokens: int = Field(..., title="Max Tokens")


class ORMContextRequest(BaseModel):
    provider: str = Field(..., title="Provider")
    model_id: str = Field(..., title="Model Id")
    query: str = Field(..., title="Query")
    llm_output_specs: LlmOutputSpecs
    user_llm_config: Optional[UserLlmConfig] = Field(None, title="User Llm Config")


class MultiQueryRequest(BaseModel):
    provider: str = Field(..., title="Provider")
    model_id: str = Field(..., title="Model Id")
    multiplier: int = Field(..., title="Multiplier")
    query: str = Field(..., title="Query")
    user_llm_config: Optional[UserLlmConfig] = Field(None, title="User Llm Config")

class MultiQueryResponse(BaseModel):
    variants: List[str] = Field(..., title="Variants")


class PromptRequest(BaseModel):
    prompt: str = Field(..., title="Prompt")


class PromptResponse(BaseModel):
    response: str = Field(..., title="Response")


class UserLlmTestRequest(BaseModel):
    model_id: str = Field(..., title="Model Id")
    label: str = Field(..., title="Label")
    api_base: str = Field(..., title="API Base URL")
    connection_params: Dict[str, Any] = Field(..., title="Litellm Params")
    max_tokens: int = Field(..., title="Max Tokens")

