[handlers]
keys=rotatingFileHandler,consoleHandler

[formatters]
keys=jsonFormatter

[logger_root]
level=DEBUG
handlers=rotatingFileHandler,consoleHandler

[handler_rotatingFileHandler]
class=handlers.RotatingFileHandler
level=NOTSET
formatter=jsonFormatter
args=('./logs/dev.log', 'a', 5000000, 3)

[handler_consoleHandler]
class=StreamHandler
level=NOTSET
formatter=jsonFormatter
args=(sys.stdout,)

[formatter_jsonFormatter]
class=shared.logging.CustomJsonFormatter
format=%(asctime)s %(name)s %(funcName)s %(levelname)s %(message)s