# generated by datamodel-codegen:
#   filename:  openapi.patched.json
#   timestamp: 2026-03-05T12:31:24+00:00

from enum import StrEnum

from pydantic import UUID4, AwareDatetime, BaseModel, Field, RootModel, SecretStr


class CertCreateRequest(BaseModel):
    purpose: str | None = Field(default=None, title="Purpose")
    key_size: int | None = Field(default=None, title="Key Size")
    validity_in_months: int | None = Field(default=None, title="Validity In Months")


class CrawlResponse(BaseModel):
    integration_registry_repr: str = Field(..., title="Integration Registry Repr")
    integrations_enum: list[str] = Field(..., title="Integrations Enum")
    schemas_enum: list[str] = Field(..., title="Schemas Enum")
    tables_enum: list[str] = Field(..., title="Tables Enum")
    columns_enum: list[str] = Field(..., title="Columns Enum")
    filter_op_enum: list[str] = Field(..., title="Filter Op Enum")
    agg_funcs_enum: list[str] = Field(..., title="Agg Funcs Enum")


class FilteredCrawlRequest(BaseModel):
    integrations: list[UUID4] = Field(..., title="Integrations")
    schemas: dict[str, list[str]] = Field(..., title="Schemas")
    tables: dict[str, list[str]] = Field(..., title="Tables")


class IntegrationStatsResponse(BaseModel):
    integration_ids: list[UUID4] = Field(..., title="Integration Ids")
    integration_count: int = Field(..., title="Integration Count")


class IntegrationUpdateRequest(BaseModel):
    connection_name: str | None = Field(default=None, title="Connection Name")
    host: str | None = Field(default=None, title="Host")
    port: int | None = Field(default=None, title="Port")
    database_name: str | None = Field(default=None, title="Database Name")
    autosync_on: bool | None = Field(default=None, title="Autosync On")


class Auth(StrEnum):
    iam = "iam"
    secret = "secret"
    cert = "cert"
    password_native = "password_native"
    password_proxy = "password_proxy"
    jwt = "jwt"


class CertState(StrEnum):
    pending = "PENDING"
    asigned = "ASIGNED"
    active = "ACTIVE"
    revoked = "REVOKED"
    expired = "EXPIRED"
    orphaned = "ORPHANED"


class Cloud(StrEnum):
    aws = "aws"
    azure = "azure"
    gcp = "gcp"
    snowflake_managed = "snowflake_managed"


class DB(StrEnum):
    mysql = "mysql"
    sqlserver = "sqlserver"
    postgresql = "postgresql"
    snowflake = "snowflake"


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")


class CertProfile(BaseModel):
    id: UUID4 = Field(..., title="Id")
    state: CertState
    cert_kid: str = Field(..., title="Cert Kid")
    cert_name: str = Field(..., title="Cert Name")
    public_cert_pem: str = Field(..., title="Public Cert Pem")
    thumbprint_sha256: str = Field(..., title="Thumbprint Sha256")
    not_before: AwareDatetime = Field(..., title="Not Before")
    not_after: AwareDatetime = Field(..., title="Not After")
    created_at: AwareDatetime = Field(..., title="Created At")
    assigned_at: AwareDatetime | None = Field(default=None, title="Assigned At")
    activated_at: AwareDatetime | None = Field(default=None, title="Activated At")
    revoked_at: AwareDatetime | None = Field(default=None, title="Revoked At")


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(default=None, title="Detail")


class IntegrationConnectionProfile(BaseModel):
    auth: Auth
    cloud: Cloud
    db: DB
    host: str = Field(..., title="Host")
    database_name: str = Field(..., title="Database Name")
    port: int | None = Field(default=None, title="Port")
    warehouse: str | None = Field(default=None, title="Warehouse")
    username: str | None = Field(default=None, title="Username")
    password: str | None = Field(default=None, title="Password")
    client_secret: str | None = Field(default=None, title="Client Secret")
    aws_external_id: str | None = Field(default=None, title="Aws External Id")
    aws_role_arn: str | None = Field(default=None, title="Aws Role Arn")
    snowflake_private_key: str | None = Field(
        default=None, title="Snowflake Private Key"
    )
    azure_cert_kid: str | None = Field(default=None, title="Azure Cert Kid")
    azure_cert_name: str | None = Field(default=None, title="Azure Cert Name")
    tenant_id: str | None = Field(default=None, title="Tenant Id")
    client_id: str | None = Field(default=None, title="Client Id")
    region: str | None = Field(default=None, title="Region")


class IntegrationCreateRequest(BaseModel):
    auth: Auth
    cloud: Cloud
    db: DB
    connection_name: str = Field(..., title="Connection Name")
    host: str = Field(..., title="Host")
    database_name: str = Field(..., title="Database Name")
    port: int | None = Field(default=None, title="Port")
    warehouse: str | None = Field(default=None, title="Warehouse")
    tenant_id: str | None = Field(default=None, title="Tenant Id")
    client_id: str | None = Field(default=None, title="Client Id")
    region: str | None = Field(default=None, title="Region")
    kek_kid: str | None = Field(default=None, title="Kek Kid")
    azure_cert_kid: str | None = Field(default=None, title="Azure Cert Kid")
    azure_cert_name: str | None = Field(default=None, title="Azure Cert Name")
    azure_public_key_pem: str | None = Field(default=None, title="Azure Public Key Pem")
    snowflake_public_key_pem: str | None = Field(
        default=None, title="Snowflake Public Key Pem"
    )
    username: SecretStr | None = Field(default=None, title="Username")
    password: SecretStr | None = Field(default=None, title="Password")
    client_secret: SecretStr | None = Field(default=None, title="Client Secret")
    aws_role_arn: SecretStr | None = Field(default=None, title="Aws Role Arn")
    aws_external_id: SecretStr | None = Field(default=None, title="Aws External Id")
    snowflake_private_key: SecretStr | None = Field(
        default=None, title="Snowflake Private Key"
    )
    autosync_on: bool = Field(default=True, title="Autosync On")


class IntegrationProfile(BaseModel):
    id: UUID4 = Field(..., title="Id")
    auth: Auth
    cloud: Cloud
    db: DB
    connection_name: str = Field(..., title="Connection Name")
    database_name: str = Field(..., title="Database Name")
    host: str = Field(..., title="Host")
    port: int | None = Field(default=None, title="Port")
    autosync_on: bool = Field(default=True, title="Autosync On")


class ResponseGetProfilesV1IntegrationOrganizationsOrganizationIdUsersUserIdIntegrationsProfilesGet(
    RootModel[list[IntegrationProfile]]
):
    root: list[IntegrationProfile] = Field(
        ...,
        title="Response Get Profiles V1 Integration Organizations  Organization Id  Users  User Id  Integrations Profiles Get",
    )


class ResponseGetCertProfilesV1IntegrationOrganizationsOrganizationIdUsersUserIdIntegrationsCertificatesProfilesGet(
    RootModel[list[CertProfile]]
):
    root: list[CertProfile] = Field(
        ...,
        title="Response Get Cert Profiles V1 Integration Organizations  Organization Id  Users  User Id  Integrations Certificates Profiles Get",
    )
