"""create tables

Revision ID: 57c2b59760fa
Revises: 
Create Date: 2026-09-13 17:04:23.708924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57c2b59760fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datastores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('auth', sa.Enum('iam', 'secret', 'cert', 'password_native', 'password_proxy', 'jwt', name='auth', schema='integration'), nullable=False),
    sa.Column('cloud', sa.Enum('aws', 'azure', 'gcp', 'snowflake_managed', name='cloud', schema='integration'), nullable=False),
    sa.Column('db', sa.Enum('mysql', 'sqlserver', 'postgresql', 'snowflake', name='db', schema='integration'), nullable=False),
    sa.Column('connection_name', sa.Text(), nullable=False),
    sa.Column('descr', sa.Text(), nullable=False),
    sa.Column('host', sa.Text(), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('database_name', sa.Text(), nullable=False),
    sa.Column('warehouse', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Text(), nullable=True),
    sa.Column('region', sa.Text(), nullable=True),
    sa.Column('azure_cert_kid', sa.Text(), nullable=True),
    sa.Column('azure_cert_name', sa.Text(), nullable=True),
    sa.Column('azure_public_key_pem', sa.Text(), nullable=True),
    sa.Column('snowflake_public_key_pem', sa.Text(), nullable=True),
    sa.Column('kek_kid', sa.Text(), nullable=False),
    sa.Column('autosync_on', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='integration'
    )
    op.create_index('idx_datastores_org_user', 'datastores', ['organization_id', 'user_id'], unique=False, schema='integration')
    op.create_index(op.f('ix_integration_datastores_organization_id'), 'datastores', ['organization_id'], unique=False, schema='integration')
    op.create_index(op.f('ix_integration_datastores_user_id'), 'datastores', ['user_id'], unique=False, schema='integration')
    op.create_table('user_llm',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('api_base', sa.Text(), nullable=False),
    sa.Column('model_id', sa.Text(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('encrypted_connection_params', postgresql.BYTEA(), nullable=False),
    sa.Column('nonce', postgresql.BYTEA(), nullable=False),
    sa.Column('tag', postgresql.BYTEA(), nullable=False),
    sa.Column('wrapped_dek', postgresql.BYTEA(), nullable=False),
    sa.Column('enc_alg', sa.Text(), nullable=False),
    sa.Column('wrap_alg', sa.Text(), nullable=False),
    sa.Column('encoding', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('kek_kid', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', 'model_id', 'api_base', name='uq_user_hosted_llm_user_model_endpoint'),
    schema='integration'
    )
    op.create_index('idx_user_hosted_llm_org_user', 'user_llm', ['organization_id', 'user_id'], unique=False, schema='integration')
    op.create_index(op.f('ix_integration_user_llm_organization_id'), 'user_llm', ['organization_id'], unique=False, schema='integration')
    op.create_index(op.f('ix_integration_user_llm_user_id'), 'user_llm', ['user_id'], unique=False, schema='integration')
    op.create_table('datastore_certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('datastore_id', sa.UUID(), nullable=True),
    sa.Column('state', sa.Enum('PENDING', 'ASSIGNED', 'ACTIVE', 'REVOKED', 'EXPIRED', 'ORPHANED', name='cert_state', schema='integration'), server_default=sa.text("'PENDING'::integration.cert_state"), nullable=False),
    sa.Column('cert_kid', sa.Text(), nullable=False),
    sa.Column('cert_name', sa.Text(), nullable=False),
    sa.Column('public_cert_pem', sa.Text(), nullable=False),
    sa.Column('thumbprint_sha256', sa.CHAR(length=64), nullable=False),
    sa.Column('not_before', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('not_after', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('activated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['datastore_id'], ['integration.datastores.id'], name='fk_datastore_certificates_datastore_id'),
    sa.PrimaryKeyConstraint('id'),
    schema='integration'
    )
    op.create_index('idx_certificates_org_user', 'datastore_certificates', ['organization_id', 'user_id'], unique=False, schema='integration')
    op.create_index(op.f('ix_integration_datastore_certificates_organization_id'), 'datastore_certificates', ['organization_id'], unique=False, schema='integration')
    op.create_index(op.f('ix_integration_datastore_certificates_user_id'), 'datastore_certificates', ['user_id'], unique=False, schema='integration')
    op.create_table('datastore_secrets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('datastore_id', sa.UUID(), nullable=False),
    sa.Column('secret_type', sa.Enum('username', 'password', 'client_secret', 'aws_role_arn', 'aws_external_id', 'snowflake_private_key', name='secret_type', schema='integration'), nullable=False),
    sa.Column('ciphertext', postgresql.BYTEA(), nullable=False),
    sa.Column('nonce', postgresql.BYTEA(), nullable=False),
    sa.Column('tag', postgresql.BYTEA(), nullable=False),
    sa.Column('wrapped_dek', postgresql.BYTEA(), nullable=False),
    sa.Column('enc_alg', sa.Text(), nullable=False),
    sa.Column('wrap_alg', sa.Text(), nullable=False),
    sa.Column('encoding', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_accessed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['datastore_id'], ['integration.datastores.id'], name='fk_datastore_secrets_datastore_id'),
    sa.PrimaryKeyConstraint('id'),
    schema='integration'
    )
    op.create_index('idx_secrets_org_user', 'datastore_secrets', ['organization_id', 'user_id'], unique=False, schema='integration')
    op.create_index(op.f('ix_integration_datastore_secrets_organization_id'), 'datastore_secrets', ['organization_id'], unique=False, schema='integration')
    op.create_index(op.f('ix_integration_datastore_secrets_user_id'), 'datastore_secrets', ['user_id'], unique=False, schema='integration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_datastore_secrets_user_id'), table_name='datastore_secrets', schema='integration')
    op.drop_index(op.f('ix_integration_datastore_secrets_organization_id'), table_name='datastore_secrets', schema='integration')
    op.drop_index('idx_secrets_org_user', table_name='datastore_secrets', schema='integration')
    op.drop_table('datastore_secrets', schema='integration')
    op.drop_index(op.f('ix_integration_datastore_certificates_user_id'), table_name='datastore_certificates', schema='integration')
    op.drop_index(op.f('ix_integration_datastore_certificates_organization_id'), table_name='datastore_certificates', schema='integration')
    op.drop_index('idx_certificates_org_user', table_name='datastore_certificates', schema='integration')
    op.drop_table('datastore_certificates', schema='integration')
    op.drop_index(op.f('ix_integration_user_llm_user_id'), table_name='user_llm', schema='integration')
    op.drop_index(op.f('ix_integration_user_llm_organization_id'), table_name='user_llm', schema='integration')
    op.drop_index('idx_user_hosted_llm_org_user', table_name='user_llm', schema='integration')
    op.drop_table('user_llm', schema='integration')
    op.drop_index(op.f('ix_integration_datastores_user_id'), table_name='datastores', schema='integration')
    op.drop_index(op.f('ix_integration_datastores_organization_id'), table_name='datastores', schema='integration')
    op.drop_index('idx_datastores_org_user', table_name='datastores', schema='integration')
    op.drop_table('datastores', schema='integration')
    # ### end Alembic commands ###
