# generated by datamodel-codegen:
#   filename:  openapi.patched.json
#   timestamp: 2026-01-17T20:41:17+00:00

from pydantic import BaseModel, Field


class EmbeddingResponse(BaseModel):
    embedding: list[float] = Field(..., title="Embedding")


class QueryEmbeddingRequest(BaseModel):
    datastream: str = Field(..., title="Datastream")


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(default=None, title="Detail")
