# generated by datamodel-codegen:
#   filename:  openapi.patched.json
#   timestamp: 2026-01-18T16:29:29+00:00

from enum import StrEnum

from pydantic import UUID4, AwareDatetime, BaseModel, Field, RootModel, SecretStr


class AIQueryRequest(BaseModel):
    provider: str = Field(..., title="Provider")
    model_id: str = Field(..., title="Model Id")
    prompt: str = Field(..., title="Prompt")


class AIQueryResponse(BaseModel):
    sql: str = Field(..., title="Sql")
    data: list[dict[str, str]] = Field(..., title="Data")


class CertCreateRequest(BaseModel):
    purpose: str | None = Field(default=None, title="Purpose")
    key_size: int | None = Field(default=None, title="Key Size")
    validity_in_months: int | None = Field(default=None, title="Validity In Months")


class IntegrationTestResponse(BaseModel):
    success: bool = Field(..., title="Success")


class IntegrationUpdateRequest(BaseModel):
    connection_name: str | None = Field(..., title="Connection Name")
    host: str | None = Field(..., title="Host")
    port: int | None = Field(..., title="Port")
    database_name: str | None = Field(..., title="Database Name")
    autosync_on: bool | None = Field(..., title="Autosync On")


class ModelInfo(BaseModel):
    provider: str = Field(..., title="Provider")
    model_id: str = Field(..., title="Model Id")
    label: str = Field(..., title="Label")
    tags: list[str] = Field(..., title="Tags")


class UserProfile(BaseModel):
    id: UUID4 = Field(..., title="Id")
    email: str = Field(..., title="Email")
    name: str = Field(..., title="Name")
    organization: str = Field(..., title="Organization")
    organization_id: UUID4 = Field(..., title="Organization Id")


class UserStats(BaseModel):
    integrations_number: int = Field(..., title="Integrations Number")
    vectors_number: int = Field(..., title="Vectors Number")


class VectorProfileResponse(BaseModel):
    integration_id: UUID4 = Field(..., title="Integration Id")
    schema_name: str = Field(..., title="Schema Name")
    table_name: str = Field(..., title="Table Name")
    table_meta: str = Field(..., title="Table Meta")


class Auth(StrEnum):
    iam = "iam"
    secret = "secret"
    cert = "cert"
    password_native = "password_native"
    password_proxy = "password_proxy"
    jwt = "jwt"


class CertState(StrEnum):
    pending = "PENDING"
    assigned = "ASSIGNED"
    active = "ACTIVE"
    revoked = "REVOKED"
    expired = "EXPIRED"
    orphaned = "ORPHANED"


class Cloud(StrEnum):
    aws = "aws"
    azure = "azure"
    gcp = "gcp"
    snowflake_managed = "snowflake_managed"


class DB(StrEnum):
    mysql = "mysql"
    sqlserver = "sqlserver"
    postgresql = "postgresql"
    snowflake = "snowflake"


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")


class ResponseGetGenModelsV1NextploreOrchestratorAiOrmModelsGet(
    RootModel[list[ModelInfo]]
):
    root: list[ModelInfo] = Field(
        ..., title="Response Get Gen Models V1 Nextplore Orchestrator Ai Orm Models Get"
    )


class ResponseGetVectorProfilesV1NextploreOrchestratorIntegrationsIntegrationIdVectorsProfilesGet(
    RootModel[list[VectorProfileResponse]]
):
    root: list[VectorProfileResponse] = Field(
        ...,
        title="Response Get Vector Profiles V1 Nextplore Orchestrator Integrations  Integration Id  Vectors Profiles Get",
    )


class CertProfile(BaseModel):
    id: UUID4 = Field(..., title="Id")
    state: CertState
    cert_kid: str = Field(..., title="Cert Kid")
    cert_name: str = Field(..., title="Cert Name")
    public_cert_pem: str = Field(..., title="Public Cert Pem")
    thumbprint_sha256: str = Field(..., title="Thumbprint Sha256")
    not_before: AwareDatetime = Field(..., title="Not Before")
    not_after: AwareDatetime = Field(..., title="Not After")
    created_at: AwareDatetime = Field(..., title="Created At")
    assigned_at: AwareDatetime | None = Field(default=None, title="Assigned At")
    activated_at: AwareDatetime | None = Field(default=None, title="Activated At")
    revoked_at: AwareDatetime | None = Field(default=None, title="Revoked At")


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(default=None, title="Detail")


class IntegrationCreateRequest(BaseModel):
    auth: Auth
    cloud: Cloud
    db: DB
    connection_name: str = Field(..., title="Connection Name")
    host: str = Field(..., title="Host")
    database_name: str = Field(..., title="Database Name")
    port: int | None = Field(default=None, title="Port")
    warehouse: str | None = Field(default=None, title="Warehouse")
    tenant_id: str | None = Field(default=None, title="Tenant Id")
    client_id: str | None = Field(default=None, title="Client Id")
    region: str | None = Field(default=None, title="Region")
    kek_kid: str | None = Field(default=None, title="Kek Kid")
    azure_cert_kid: str | None = Field(default=None, title="Azure Cert Kid")
    azure_cert_name: str | None = Field(default=None, title="Azure Cert Name")
    azure_public_key_pem: str | None = Field(default=None, title="Azure Public Key Pem")
    snowflake_public_key_pem: str | None = Field(
        default=None, title="Snowflake Public Key Pem"
    )
    username: SecretStr | None = Field(default=None, title="Username")
    password: SecretStr | None = Field(default=None, title="Password")
    client_secret: SecretStr | None = Field(default=None, title="Client Secret")
    aws_role_arn: SecretStr | None = Field(default=None, title="Aws Role Arn")
    aws_external_id: SecretStr | None = Field(default=None, title="Aws External Id")
    snowflake_private_key: SecretStr | None = Field(
        default=None, title="Snowflake Private Key"
    )
    autosync_on: bool = Field(default=True, title="Autosync On")


class IntegrationProfile(BaseModel):
    id: UUID4 = Field(..., title="Id")
    auth: Auth
    cloud: Cloud
    db: DB
    connection_name: str = Field(..., title="Connection Name")
    database_name: str = Field(..., title="Database Name")
    host: str = Field(..., title="Host")
    port: int | None = Field(default=None, title="Port")
    autosync_on: bool = Field(default=True, title="Autosync On")


class ResponseGetIntegrationProfilesV1NextploreOrchestratorIntegrationsProfilesGet(
    RootModel[list[IntegrationProfile]]
):
    root: list[IntegrationProfile] = Field(
        ...,
        title="Response Get Integration Profiles V1 Nextplore Orchestrator Integrations Profiles Get",
    )


class ResponseGetCertProfilesV1NextploreOrchestratorIntegrationsCertificatesProfilesGet(
    RootModel[list[CertProfile]]
):
    root: list[CertProfile] = Field(
        ...,
        title="Response Get Cert Profiles V1 Nextplore Orchestrator Integrations Certificates Profiles Get",
    )
