# generated by datamodel-codegen:
#   filename:  openapi.patched.json
#   timestamp: 2026-01-18T16:31:23+00:00

from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import UUID4, BaseModel, Field, RootModel


class EmbeddingQuery(BaseModel):
    embedding: list[float] = Field(..., title="Embedding")


class VectorSearchResult(BaseModel):
    vector_id: UUID4 = Field(..., title="ID")
    score: float = Field(..., title="Score")


class VectorMetadataQuery(BaseModel):
    vector_ids: list[UUID4] = Field(..., title="Vector Ids")


class TableProfile(BaseModel):
    datastore_id: UUID4 = Field(..., title="Datastore Id")
    schema_name: str = Field(..., title="Schema Name")
    table_name: str = Field(..., title="Table Name")
    table_meta: str = Field(..., title="Table Meta")


class VectorIndexStats(BaseModel):
    vector_count: int = Field(..., title="Vector Count")


class TableMetadata(BaseModel):
    datastore_id: UUID4 = Field(..., title="Datastore Id")
    schema_name: str = Field(..., title="Schema Name")
    table_name: str = Field(..., title="Table Name")
    column_names: list[str] = Field(..., title="Column Names")


class ValidationError(BaseModel):
    loc: list[str | int] = Field(..., title="Location")
    msg: str = Field(..., title="Message")
    type: str = Field(..., title="Error Type")


class ResponseGetProfilesV1VectorOrganizationsOrganizationIdUsersUserIdIntegrationsIntegrationIdVectorsProfilesGet(
    RootModel[list[TableProfile]]
):
    root: list[TableProfile] = Field(
        ...,
        title="Response Get Profiles V1 Vector Organizations  Organization Id  Users  User Id  Integrations  Integration Id  Vectors Profiles Get",
    )


class HTTPValidationError(BaseModel):
    detail: list[ValidationError] | None = Field(default=None, title="Detail")


class VectorMetadata(BaseModel):
    vector_id: UUID4 = Field(..., title="Vector Id")
    datastore_id: UUID4 = Field(..., title="Datastore Id")
    schema_name: str = Field(..., title="Schema Name")
    table_name: str = Field(..., title="Table Name")
    table_metadata: TableMetadata


class ResponseGetMetaV1VectorOrganizationsOrganizationIdUsersUserIdIntegrationsVectorsMetaGet(
    RootModel[list[VectorMetadata]]
):
    root: list[VectorMetadata] = Field(
        ...,
        title="Response Get Meta V1 Vector Organizations  Organization Id  Users  User Id  Integrations Vectors Meta Get",
    )


class SemanticCacheLookupResult(BaseModel):
    hit: bool = Field(..., title="Hit")
    json_payload: dict[str, Any] | None = Field(default=None, title="JSON Payload")


class SemanticCacheEntry(BaseModel):
    embedding: list[float] = Field(..., title="Embedding")
    json_payload: dict[str, Any] = Field(..., title="JSON Payload")
    expires_at: datetime = Field(..., title="Expires At")
    provider: str = Field(..., title="Provider")
    model_id: str = Field(..., title="Model Id")
    model_ref_id: UUID4 | None = Field(default=None, title="Model Ref Id")


class SemanticCacheLookupQuery(BaseModel):
    embedding: list[float] = Field(..., title="Embedding")
    provider: str = Field(..., title="Provider")
    model_id: str = Field(..., title="Model Id")
    model_ref_id: UUID4 | None = Field(default=None, title="Model Ref Id")
