{
    "type": "record",
    "namespace": "com.nextplore.integration",
    "name": "IntegrationCreated",
    "fields": [
        {"name": "event_name", "type": "string"},
        {"name": "version", "type": "string"},
        {"name": "event_id", "type": {"type": "string", "logicalType": "uuid"}},
        {"name": "timestamp", "type": {"type": "long", "logicalType": "timestamp-micros"}},
        {"name": "user_id", "type": {"type": "string", "logicalType": "uuid"}},
        {"name": "organization_id", "type": {"type": "string", "logicalType": "uuid"}},
        {"name": "integration_id", "type": {"type": "string", "logicalType": "uuid"}}
    ]
}
