#!/usr/bin/env bash
set -euo pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  -- schemas generation
  CREATE SCHEMA IF NOT EXISTS auth;
  CREATE SCHEMA IF NOT EXISTS integration;
  CREATE SCHEMA IF NOT EXISTS vector;
  CREATE SCHEMA IF NOT EXISTS notification;

  --  role per service, each scoped to its own schema
  DO \$\$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DB_USR_ORCHESTRATION_SERVICE}') THEN
      CREATE ROLE ${DB_USR_ORCHESTRATION_SERVICE} LOGIN PASSWORD '${DB_PWD_ORCHESTRATION_SERVICE}';
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DB_USR_INTEGRATION_SERVICE}') THEN
      CREATE ROLE ${DB_USR_INTEGRATION_SERVICE} LOGIN PASSWORD '${DB_PWD_INTEGRATION_SERVICE}';
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DB_USR_VECTOR_SERVICE}') THEN
      CREATE ROLE ${DB_USR_VECTOR_SERVICE} LOGIN PASSWORD '${DB_PWD_VECTOR_SERVICE}';
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DB_USR_NOTIFICATION_SERVICE}') THEN
      CREATE ROLE ${DB_USR_NOTIFICATION_SERVICE} LOGIN PASSWORD '${DB_PWD_NOTIFICATION_SERVICE}';
    END IF;
  END
  \$\$;


  -- nextplore_orchestrator owns auth, and also notification --
  GRANT USAGE, CREATE ON SCHEMA auth TO ${DB_USR_ORCHESTRATION_SERVICE};
  GRANT USAGE, CREATE ON SCHEMA notification TO ${DB_USR_ORCHESTRATION_SERVICE};

  GRANT USAGE, CREATE ON SCHEMA integration TO ${DB_USR_INTEGRATION_SERVICE};
  GRANT USAGE, CREATE ON SCHEMA vector TO ${DB_USR_VECTOR_SERVICE};

  -- notification service ownership
  GRANT USAGE ON SCHEMA notification TO ${DB_USR_NOTIFICATION_SERVICE};
  ALTER DEFAULT PRIVILEGES FOR ROLE ${DB_USR_ORCHESTRATION_SERVICE} IN SCHEMA notification
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${DB_USR_NOTIFICATION_SERVICE};
EOSQL